services:
  admin:
    platform: linux/amd64
    image: registry.britenet.com.pl/frontend/procareful/admin:dev
    build:
      dockerfile: ./apps/procareful-admin/Dockerfile
      context: .
    ports:
      - '127.0.0.1:8080:80'
    restart: always
  senior:
    platform: linux/amd64
    image: registry.britenet.com.pl/frontend/procareful/senior:dev
    build:
      dockerfile: ./apps/procareful/Dockerfile
      context: .
    ports:
      - '127.0.0.1:8081:80'
    restart: always
